# this file should be included by the projects top level Makefile

include $(build_dir)/variables.mk
include $(build_dir)/attributes.mk
include $(build_dir)/commands.mk
include $(build_dir)/functions.mk
include $(build_dir)/implicit-rules.mk
include $(build_dir)/module-helper.mk
include $(build_dir)/modules.mk


# these are variables filled in by the module.mk files

# all the sources
sources :=
object_files :=
cxx_progs :=
cxx_shlibs :=

# all the dependency files generated from the object files
dependencies := $(shell find -name '*.d')

# module.mk files
modules := $(shell find -name 'module.mk')


# clean_files

# files to clean out with the clean-files target


# bin_dir

# directory to copy binaries to


# lib_dir

# directory to copy libraries to


# obj_dir

# directory to place the object files in.  The path specified here is
# relative to the object file's source file


# list of directories with headers
include_dirs +=

.PHONY: clean clean-build clean-targets clean-files clean-dirs obj_dirs src_cp programs libraries

ifneq ($(MAKECMDGOALS),clean)
include $(dependencies)
endif

include $(modules)

libraries: obj_dirs $(cxx_shlibs)
programs: obj_dirs $(cxx_progs)
plugins: $(plugins)

obj_dirs:
	@mkdir -p $(sort $(dir $(object_files)))

src_cp:
	$(foreach src,$(sources),\
                  $(if $(src)_cp_dest,$(call cp,$(src),$($(src)_cp_dest))))

# cleans out all the files generated by the build including the object
# file directories
clean-build:
	rm -f $(shell find -name '*.$(cxx_prog_obj)' -o \
                           -name '*.d' -o \
                           -name '*.$(cxx_shlib_obj)' -o \
                           -name '*~')

	$(if $(obj_dir),-rmdir $(sort $(dir $(object_files))))


# removes the targets
clean-targets:
	rm -f $(cxx_progs) $(cxx_shlibs)


# removes the binary directory and the library directory
clean-dirs:
	$(if $(bin_dir),rm -f $(addprefix $(bin_dir)/,$(notdir $(cxx_progs))))
	$(if $(lib_dir),rm -f $(addprefix $(lib_dir)/,$(notdir $(cxx_shlibs))))
	$(if $(bin_dir),-rmdir $(bin_dir))
	$(if $(lib_dir),-rmdir $(lib_dir))


# removes all the files specified in the clean_files variable
clean-files:
	rm -f $(clean_files)


clean-all: clean-build clean-targets clean-dirs clean-files
